# Notes
# - Secret variables do not work for pull request builds, if we want to deploy from such builds, we need some other way to handle Git and Nuget personal access tokens

parameters:
  buildConfiguration: "Release"
  runInheritDoc: true
  runTests: true
  runCodeCoverage: true
  codecovKey: "$(codecovKey)"
  changelogPath: "CHANGELOG.md"
  versionHeaderPattern: '^##[ \t]*\[(\d+\.\d+\.\d+[0-9A-Za-z-.]*)\]'
  # TODO allow for multiple restore endpoints
  nugetRestoreEndpoint: ""
  nugetRestorePat: ""
  nugetPushEndpoint: ""
  nugetPushPat: "$(nugetPushPat)"
  nugetDistUrl: "https://dist.nuget.org/win-x86-commandline/v4.7.1/nuget.exe"
  githubPat: "$(githubPat)"

jobs:
# Build
- job: "Build"
  pool:
    vmImage: "vs2017-win2016"
  steps:
  - ${{if ne(parameters.nugetRestoreEndpoint, '')}}:
    - template: "../shared/set-nuget-restore-endpoint.yml"
      parameters: 
        nugetRestoreEndpoint: ${{parameters.nugetRestoreEndpoint}}
        nugetRestorePat: ${{parameters.nugetRestorePat}}
        nugetDistUrl: ${{parameters.nugetDistUrl}}
  - powershell: |
      function Render-Body { $input | foreach{@{value=$_}} | Format-Table -Property @{Expression={" "}},value -HideTableHeader -wrap}

      # Place cache in working directory so that it is uploaded to pipeline artifacts
      $env:NUGET_PACKAGES=$env:SYSTEM_DEFAULTWORKINGDIRECTORY + "/packages"

      "Restoring packages:"
      dotnet restore | Render-Body

      "Building solution:"
      dotnet build --no-restore --configuration Release -p:CopyLocalLockFileAssemblies=true | Render-Body

      if("${{parameters.runInheritDoc}}" -eq 'true'){
        "Installing InheritDoc:"
        dotnet tool install InheritDocTool --tool-path . | Render-Body # Install to current dir https://github.com/dotnet/cli/issues/8368

        "Running InheritDoc:"
        .\InheritDoc.exe -b src -o | Render-Body

        # We won't be needing InheritDoc again in the pipeline
        remove-item .\InheritDoc.exe
        remove-item .\.store -recurse
      }
    displayName: "Build"
  - template: "../shared/publish-working-directory.yml"
# Test
- ${{if eq(parameters.runTests, 'true')}}:
  - job: "WindowsTests"
    dependsOn: "Build"
    pool:
      vmImage: "vs2017-win2016"
    steps:
    # Skip checking out the default repository resource
    - checkout: "none"
    - template: "../shared/download-working-directory.yml"
    # Test and handle code coverage report
    - powershell: |
        function Render-Body { $input | foreach{@{value=$_}} | Format-Table -Property @{Expression={" "}},value -HideTableHeader -wrap}

        # Make sure dotnet knows to look for packages in ./packages
        $env:NUGET_PACKAGES=$env:SYSTEM_DEFAULTWORKINGDIRECTORY + "/packages"

        "Running tests:"
        dotnet test --no-build --no-restore --configuration Release --logger trx --results-directory $(Agent.TempDirectory) -p:CollectCoverage="${{parameters.runCodeCoverage}}" -p:CoverletOutputFormat=cobertura | Render-Body

        $reports = get-childitem coverage.cobertura.xml -Recurse | foreach{$_.fullname}
        # No reports
        if($reports.length -eq 0){
          "No code coverage reports generated..."
          exit
        }

        # Publish report to codecov
        "Publishing code coverage report(s)...`n"

        "Installing Codecov:"      
        choco install codecov --yes --no-progress --cache-location=. | Render-Body 

        "Publishing to Codecov:"
        codecov -f $reports -t "${{parameters.codecovKey}}" --required | Render-Body # Exit code 1 if uploading of report fails, otherwise it may fail silently
      displayName: "Test"
    - task: "PublishTestResults@2"
      inputs:
        testResultsFormat: "VSTest"
        testResultsFiles: "**/*.trx"
        searchFolder: "$(Agent.TempDirectory)"
        testRunTitle: "WindowsTests"
  - template: "../nuget/test.yml"
    parameters:
      name: "LinuxTests"
      vmImage: "ubuntu-16.04"
      buildConfiguration: ${{ parameters.buildConfiguration }}
  - template: "../nuget/test.yml"
    parameters:
      name: "macOSTests"
      vmImage: "macOS-10.13"
      buildConfiguration: ${{ parameters.buildConfiguration }}
# Deploy
- job: "Deploy"
  dependsOn:
  - ${{if eq(parameters.runTests, 'true')}}:
    - "WindowsTests"
    - "LinuxTests"
    - "macOSTests"
  - ${{if ne(parameters.runTests, 'true')}}:
    - "Build"
  steps:
  - checkout: "none"
  - template: "../shared/download-working-directory.yml"
  - template: "../shared/find-new-version.yml"
    parameters:
      changelogPath: ${{parameters.changelogPath}}
      versionHeaderPattern: ${{parameters.versionHeaderPattern}}
  - powershell: |
      function Render-Body { $input | foreach{@{value=$_}} | Format-Table -Property @{Expression={" "}},value -HideTableHeader -wrap}

      # Make sure dotnet knows to look for packages in ./packages
      $env:NUGET_PACKAGES=$env:SYSTEM_DEFAULTWORKINGDIRECTORY + "/packages"

      "Packing Nuget package(s):"
      dotnet pack --no-restore --no-build --configuration "${{parameters.buildConfiguration}}" -p:PackageVersion=$env:VERSION | Render-Body

      # Push using endpoint and api key
      "Pushing packages:"
      $packages = get-childitem src *.nupkg -Recurse
      foreach($package in $packages) {
        $message = dotnet nuget push $package.fullname --source "${{parameters.nugetPushEndpoint}}" --api-key "${{parameters.nugetPushPat}}"
        $message | Render-body

        # 409 returned if a package with the provided ID and version already exists - https://docs.microsoft.com/en-us/nuget/api/package-publish-resource#push-a-package
        if($lastExitCode -ne 0{
          if($message -contains ' 409 '){
            # If error occurred because package already exists, allow pipeline to continue
            "$($package.fullname) already exists..."
          }else{
            throw "An unexpected error occurred while attempting to publish $package. If it was an intermittent issue, do a manual rebuild of the same commit ($env:BUILD_SOURCEVERSION). Otherwise, rectify the issue and merge the changes into master to trigger a CI build."
          }
        }
      }

      # If we get here, any failed publish attempts were because the package already exists
      exit 0
    displayName: "Push"
    condition: and(succeeded(), ne(variables['version'], ''))
  - template: "../shared/tag-commit.yml"
    parameters:
      githubPat: ${{parameters.githubPat}}