parameters:
  iterations: 30
  buildConfiguration: "Release"
  dotnetSdkVersion: "3.0.100"
  dotnetRuntimeVersions: ["2.1.13"]
  outOfProcessTestDependencies: []
  outOfProcessBuildDependencies: []

jobs:
# Build
- job: "StressTest"
  pool:
    vmImage: "windows-2019"
  variables:
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  steps:
  - template: "restore-build-test.yml"
    parameters:
      dotnetSdkVersion: ${{parameters.dotnetSdkVersion}}
      dotnetRuntimeVersions: ${{parameters.dotnetRuntimeVersions}}
      outOfProcessTestDependencies: ${{parameters.outOfProcessTestDependencies}}
      outOfProcessBuildDependencies: ${{parameters.outOfProcessBuildDependencies}}
      buildConfiguration: ${{parameters.buildConfiguration}}
      codecovKey: ""
      runCodeCoverage: false
      runTests: false
      cacheYarnPackages: true
  ## TODO hangs after tests complete if we use powershell
  - pwsh: |
      "Running tests (${{parameters.iterations}} iterations):"
      $testProjects = get-childitem test/**/*.csproj | foreach{$_.fullname}
      $iterations = [int]"${{parameters.iterations}}"
      for ($i=0; $i -le $iterations; $i++) {
        foreach($testProject in $testProjects){
          dotnet test $testProject --no-restore --no-build --configuration ${{parameters.buildConfiguration}}
        }

        if($lastExitCode -ne 0){
          break;
        }
      }   
    displayName: "Test"