parameters:
  name: ""
  vmImage: ""
  buildConfiguration: ""

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: "Build"
  steps:
  # Skip checking out the default repository resource
  - checkout: "none"
  - template: "../shared/download-working-directory.yml"
  - task: "DotNetCoreCLI@2"
    displayName: "Test"
    inputs:
      command: "test"
      projects: "test/**/*.csproj"
      # TODO not sure why this doesn't work, possible - https://github.com/Microsoft/azure-pipelines-agent/issues/1772
      # arguments: --no-restore --no-build --configuration ${{parameters.buildConfiguration}}
      arguments: "--no-restore --no-build --configuration Release"
    # Skip dotnet first time experience
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true