parameters:
  name: ""
  vmImage: ""
  buildConfiguration: ""
  targetFramework: ""

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: "NugetBuild"
  steps:
  # Skip checking out the default repository resource
  - checkout: "none"
  - template: "../shared/download-working-directory.yml"
  - task: "DotNetCoreCLI@2"
    displayName: "Test"
    inputs:
      command: "test"
      projects: "test/**/*.csproj"
      # TODO Figure out how to run .Net Framework test assemblies on Linux/macOS using mono. For now, only allow target framework to be specified so that
      # we can run only .Net Core test assemblies on Linux/macOS.
      arguments: "--framework ${{ parameters.targetFramework }} --no-restore --no-build --configuration ${{parameters.buildConfiguration}}"
    # Skip dotnet first time experience
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true