parameters:
  nugetRestoreEndpoints: ""
  nugetRestorePats: ""
  nugetDistUrl: "https://dist.nuget.org/win-x86-commandline/v4.7.1/nuget.exe"
  netlifyPat: "$(netlifyPat)"
  srcDir: docs
jobs:
- job: "DocsBuild"
  pool:
    vmImage: "vs2017-win2016"
  steps:
  - powershell: |
      "Temporarily disabled."